# The type of the trainer
type: basic

# The machine learning model
model_name: resnet_18

# Number of epoches for local training in each communication round
epochs: 5
batch_size: 10
optimizer: SGD
lr_scheduler: LambdaLR
